name: Install tkinter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk xvfb

    - name: Run tkinter example script with Xvfb
      run: |
        timeout 60 xvfb-run --auto-servernum --server-args='-screen 0 1024x768x24' python tkinter_example.py