name: Install tkinter

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Replace with the version of Python you need

    - name: Install tkinter
      run: sudo apt-get install python3-tk

    - name: Run tkinter example script
      run: python tkinter_example.py
